package com.yusufsoysal.strava.model.enums;

import javastrava.api.v3.model.reference.StravaActivityType;

public enum ActivityType {
    RIDE, RUN, SWIM, HIKE, WALK, ALPINE_SKI, BACKCOUNTRY_SKI,
    CANOEING, CROSSFIT, EBIKE_RIDE, ELLIPTICAL, ICE_SKATE,
    INLINE_SKATE, KAYAKING, KITESURF, NORDIC_SKI, ROCK_CLIMBING,
    ROLLERSKI, ROWING, SNOWBOARD, SNOWSHOE, STAIR_STEPPER,
    STAND_UP_PADDLING, SURFING, VIRTUAL_RIDE, WEIGHT_TRAINING,
    WINDSURF, WORKOUT, YOGA, UNKNOWN
}
